// Code generated by go run gob_gen.go; DO NOT EDIT.

package bootstrap

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

// begin of bootstrap.go
func init() {
	PackageInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(PackageInfo) })
	BinaryInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(BinaryInfo) })
}

func (r PackageInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.PkgPath); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.PkgRoot); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.PackageTarget); err != nil {
		return err
	}

	if r.TestTargets == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.TestTargets)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.TestTargets); val1++ {
			if err = gobtools.EncodeString(buf, r.TestTargets[val1]); err != nil {
				return err
			}
		}
	}

	if err = r.TransitivePkgRoot.EncodeString(ctx, buf); err != nil {
		return err
	}

	if err = r.TransitivePackageTarget.EncodeString(ctx, buf); err != nil {
		return err
	}
	return err
}

func (r *PackageInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.PkgPath)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.PkgRoot)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.PackageTarget)
	if err != nil {
		return err
	}

	var val5 int
	err = gobtools.DecodeInt(buf, &val5)
	if err != nil {
		return err
	}
	if val5 != -1 {
		r.TestTargets = make([]string, val5)
		for val6 := 0; val6 < int(val5); val6++ {
			err = gobtools.DecodeString(buf, &r.TestTargets[val6])
			if err != nil {
				return err
			}
		}
	}

	if err = r.TransitivePkgRoot.DecodeString(ctx, buf); err != nil {
		return err
	}

	if err = r.TransitivePackageTarget.DecodeString(ctx, buf); err != nil {
		return err
	}

	return err
}

var PackageInfoGobRegId int16

func (r PackageInfo) GetTypeId() int16 {
	return PackageInfoGobRegId
}

func (r BinaryInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.IntermediatePath); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.InstallPath); err != nil {
		return err
	}

	if r.TestTargets == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.TestTargets)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.TestTargets); val1++ {
			if err = gobtools.EncodeString(buf, r.TestTargets[val1]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *BinaryInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.IntermediatePath)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.InstallPath)
	if err != nil {
		return err
	}

	var val4 int
	err = gobtools.DecodeInt(buf, &val4)
	if err != nil {
		return err
	}
	if val4 != -1 {
		r.TestTargets = make([]string, val4)
		for val5 := 0; val5 < int(val4); val5++ {
			err = gobtools.DecodeString(buf, &r.TestTargets[val5])
			if err != nil {
				return err
			}
		}
	}

	return err
}

var BinaryInfoGobRegId int16

func (r BinaryInfo) GetTypeId() int16 {
	return BinaryInfoGobRegId
}

// end of bootstrap.go
