// Code generated by go run gob_gen.go; DO NOT EDIT.

package blueprint

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	VariationGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(Variation) })
}

func (r Variation) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	if err := r.Encode(buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r Variation) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.Mutator); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.Variation); err != nil {
		return err
	}
	return err
}

func (r *Variation) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	return r.Decode(buf)
}

func (r *Variation) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.Mutator)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.Variation)
	if err != nil {
		return err
	}

	return err
}

var VariationGobRegId int16

func (r Variation) GetTypeId() int16 {
	return VariationGobRegId
}
