// Code generated by go run gob_gen.go; DO NOT EDIT.

package blueprint

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
	"github.com/google/blueprint/proptools"
)

func init() {
	BuildActionCacheKeyGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(BuildActionCacheKey) })
	CachedProviderGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(CachedProvider) })
	ProviderHashGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ProviderHash) })
	ModuleActionCachedDataGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ModuleActionCachedData) })
	SingletonActionCachedDataGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(SingletonActionCachedData) })
	OrderOnlyStringsCacheGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(OrderOnlyStringsCache) })
}

func (r BuildActionCacheKey) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.Id); err != nil {
		return err
	}
	return err
}

func (r *BuildActionCacheKey) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.Id)
	if err != nil {
		return err
	}

	return err
}

var BuildActionCacheKeyGobRegId int16

func (r BuildActionCacheKey) GetTypeId() int16 {
	return BuildActionCacheKeyGobRegId
}

func (r CachedProvider) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	val1 := r.Id == nil
	if err = gobtools.EncodeBool(buf, val1); err != nil {
		return err
	}
	if !val1 {
		if err = (*r.Id).Encode(ctx, buf); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.Value); err != nil {
		return err
	}
	return err
}

func (r *CachedProvider) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 bool
	if err = gobtools.DecodeBool(buf, &val2); err != nil {
		return err
	}
	if !val2 {
		var val1 providerKey
		if err = val1.Decode(ctx, buf); err != nil {
			return err
		}
		r.Id = &val1
	}

	if val5, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val5 == nil {
		r.Value = nil
	} else {
		r.Value = val5
	}

	return err
}

var CachedProviderGobRegId int16

func (r CachedProvider) GetTypeId() int16 {
	return CachedProviderGobRegId
}

func (r ProviderHash) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	val1 := r.Id == nil
	if err = gobtools.EncodeBool(buf, val1); err != nil {
		return err
	}
	if !val1 {
		if err = (*r.Id).Encode(ctx, buf); err != nil {
			return err
		}
	}

	for val2 := 0; val2 < len(r.Hash); val2++ {
		if err = gobtools.EncodeUint64(buf, r.Hash[val2]); err != nil {
			return err
		}
	}
	return err
}

func (r *ProviderHash) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 bool
	if err = gobtools.DecodeBool(buf, &val2); err != nil {
		return err
	}
	if !val2 {
		var val1 providerKey
		if err = val1.Decode(ctx, buf); err != nil {
			return err
		}
		r.Id = &val1
	}

	for val6 := 0; val6 < len(r.Hash); val6++ {
		err = gobtools.DecodeUint64(buf, &r.Hash[val6])
		if err != nil {
			return err
		}
	}

	return err
}

var ProviderHashGobRegId int16

func (r ProviderHash) GetTypeId() int16 {
	return ProviderHashGobRegId
}

func (r ModuleActionCachedData) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	for val1 := 0; val1 < len(r.InputHash); val1++ {
		if err = gobtools.EncodeUint64(buf, r.InputHash[val1]); err != nil {
			return err
		}
	}

	if r.ProviderHashes == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ProviderHashes)); err != nil {
			return err
		}
		for val2 := 0; val2 < len(r.ProviderHashes); val2++ {
			if err = r.ProviderHashes[val2].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if r.OrderOnlyStrings == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.OrderOnlyStrings)); err != nil {
			return err
		}
		for val3 := 0; val3 < len(r.OrderOnlyStrings); val3++ {
			if err = gobtools.EncodeString(buf, r.OrderOnlyStrings[val3]); err != nil {
				return err
			}
		}
	}

	if r.GlobCache == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.GlobCache)); err != nil {
			return err
		}
		for val4 := 0; val4 < len(r.GlobCache); val4++ {
			if err = r.GlobCache[val4].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *ModuleActionCachedData) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	for val3 := 0; val3 < len(r.InputHash); val3++ {
		err = gobtools.DecodeUint64(buf, &r.InputHash[val3])
		if err != nil {
			return err
		}
	}

	var val6 int
	err = gobtools.DecodeInt(buf, &val6)
	if err != nil {
		return err
	}
	if val6 != -1 {
		r.ProviderHashes = make([]ProviderHash, val6)
		for val7 := 0; val7 < int(val6); val7++ {
			if err = r.ProviderHashes[val7].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	var val10 int
	err = gobtools.DecodeInt(buf, &val10)
	if err != nil {
		return err
	}
	if val10 != -1 {
		r.OrderOnlyStrings = make([]string, val10)
		for val11 := 0; val11 < int(val10); val11++ {
			err = gobtools.DecodeString(buf, &r.OrderOnlyStrings[val11])
			if err != nil {
				return err
			}
		}
	}

	var val14 int
	err = gobtools.DecodeInt(buf, &val14)
	if err != nil {
		return err
	}
	if val14 != -1 {
		r.GlobCache = make([]globResultCache, val14)
		for val15 := 0; val15 < int(val14); val15++ {
			if err = r.GlobCache[val15].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	return err
}

var ModuleActionCachedDataGobRegId int16

func (r ModuleActionCachedData) GetTypeId() int16 {
	return ModuleActionCachedDataGobRegId
}

func (r SingletonActionCachedData) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.ProviderHashes == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ProviderHashes)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.ProviderHashes); val1++ {
			if err = r.ProviderHashes[val1].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if r.DependencyProviderHashes == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.DependencyProviderHashes)); err != nil {
			return err
		}
		for val2, val3 := range r.DependencyProviderHashes {
			if err = gobtools.EncodeInt(buf, val2); err != nil {
				return err
			}
			for val4 := 0; val4 < len(val3); val4++ {
				if err = gobtools.EncodeUint64(buf, val3[val4]); err != nil {
					return err
				}
			}
		}
	}
	return err
}

func (r *SingletonActionCachedData) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		r.ProviderHashes = make([]ProviderHash, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			if err = r.ProviderHashes[val3].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	var val5 int
	err = gobtools.DecodeInt(buf, &val5)
	if err != nil {
		return err
	}
	if val5 != -1 {
		r.DependencyProviderHashes = make(map[int]proptools.Hash, val5)
		for val6 := 0; val6 < int(val5); val6++ {
			var val7 int
			var val8 proptools.Hash
			err = gobtools.DecodeInt(buf, &val7)
			if err != nil {
				return err
			}
			for val12 := 0; val12 < len(val8); val12++ {
				err = gobtools.DecodeUint64(buf, &val8[val12])
				if err != nil {
					return err
				}
			}
			r.DependencyProviderHashes[val7] = val8
		}
	}

	return err
}

var SingletonActionCachedDataGobRegId int16

func (r SingletonActionCachedData) GetTypeId() int16 {
	return SingletonActionCachedDataGobRegId
}

func (r OrderOnlyStringsCache) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r)); err != nil {
			return err
		}
		for val1, val2 := range r {
			if err = gobtools.EncodeString(buf, val1); err != nil {
				return err
			}
			if val2 == nil {
				if err = gobtools.EncodeInt(buf, -1); err != nil {
					return err
				}
			} else {
				if err = gobtools.EncodeInt(buf, len(val2)); err != nil {
					return err
				}
				for val3 := 0; val3 < len(val2); val3++ {
					if err = gobtools.EncodeString(buf, val2[val3]); err != nil {
						return err
					}
				}
			}
		}
	}
	return err
}

func (r *OrderOnlyStringsCache) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val1 int
	err = gobtools.DecodeInt(buf, &val1)
	if err != nil {
		return err
	}
	if val1 != -1 {
		(*r) = make(map[string][]string, val1)
		for val2 := 0; val2 < int(val1); val2++ {
			var val3 string
			var val4 []string
			err = gobtools.DecodeString(buf, &val3)
			if err != nil {
				return err
			}
			var val7 int
			err = gobtools.DecodeInt(buf, &val7)
			if err != nil {
				return err
			}
			if val7 != -1 {
				val4 = make([]string, val7)
				for val8 := 0; val8 < int(val7); val8++ {
					err = gobtools.DecodeString(buf, &val4[val8])
					if err != nil {
						return err
					}
				}
			}
			(*r)[val3] = val4
		}
	}

	return err
}

var OrderOnlyStringsCacheGobRegId int16

func (r OrderOnlyStringsCache) GetTypeId() int16 {
	return OrderOnlyStringsCacheGobRegId
}
