// Code generated by go run gob_gen.go; DO NOT EDIT.

package blueprint

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	BuildActionCacheKeyGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(BuildActionCacheKey) })
	CachedProviderGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(CachedProvider) })
	BuildActionCachedDataGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(BuildActionCachedData) })
	BuildActionCacheGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(BuildActionCache) })
	OrderOnlyStringsCacheGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(OrderOnlyStringsCache) })
}

func (r BuildActionCacheKey) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.Id); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.InputHash); err != nil {
		return err
	}
	return err
}

func (r *BuildActionCacheKey) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.Id)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[uint64](buf, &r.InputHash)
	if err != nil {
		return err
	}

	return err
}

var BuildActionCacheKeyGobRegId int16

func (r BuildActionCacheKey) GetTypeId() int16 {
	return BuildActionCacheKeyGobRegId
}

func (r CachedProvider) Encode(buf *bytes.Buffer) error {
	var err error

	val1 := r.Id == nil
	if err = gobtools.EncodeSimple(buf, val1); err != nil {
		return err
	}
	if !val1 {
		if err = (*r.Id).Encode(buf); err != nil {
			return err
		}
	}

	val2 := r.Value == nil
	if err = gobtools.EncodeSimple(buf, val2); err != nil {
		return err
	}
	if !val2 {
		if err = gobtools.EncodeInterface(buf, (*r.Value)); err != nil {
			return err
		}
	}
	return err
}

func (r *CachedProvider) Decode(buf *bytes.Reader) error {
	var err error

	var val2 bool
	if err = gobtools.DecodeSimple(buf, &val2); err != nil {
		return err
	}
	if !val2 {
		var val1 providerKey
		if err = val1.Decode(buf); err != nil {
			return err
		}
		r.Id = &val1
	}

	var val5 bool
	if err = gobtools.DecodeSimple(buf, &val5); err != nil {
		return err
	}
	if !val5 {
		var val4 any
		if val7, err := gobtools.DecodeInterface(buf); err != nil {
			return err
		} else if val7 == nil {
			val4 = nil
		} else {
			val4 = val7
		}
		r.Value = &val4
	}

	return err
}

var CachedProviderGobRegId int16

func (r CachedProvider) GetTypeId() int16 {
	return CachedProviderGobRegId
}

func (r BuildActionCachedData) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeSimple(buf, int32(len(r.Providers))); err != nil {
		return err
	}
	for val1 := 0; val1 < len(r.Providers); val1++ {
		if err = r.Providers[val1].Encode(buf); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.OrderOnlyStrings))); err != nil {
		return err
	}
	for val2 := 0; val2 < len(r.OrderOnlyStrings); val2++ {
		if err = gobtools.EncodeString(buf, r.OrderOnlyStrings[val2]); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.GlobCache))); err != nil {
		return err
	}
	for val3 := 0; val3 < len(r.GlobCache); val3++ {
		if err = r.GlobCache[val3].Encode(buf); err != nil {
			return err
		}
	}
	return err
}

func (r *BuildActionCachedData) Decode(buf *bytes.Reader) error {
	var err error

	var val2 int32
	err = gobtools.DecodeSimple[int32](buf, &val2)
	if err != nil {
		return err
	}
	if val2 > 0 {
		r.Providers = make([]CachedProvider, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			if err = r.Providers[val3].Decode(buf); err != nil {
				return err
			}
		}
	}

	var val6 int32
	err = gobtools.DecodeSimple[int32](buf, &val6)
	if err != nil {
		return err
	}
	if val6 > 0 {
		r.OrderOnlyStrings = make([]string, val6)
		for val7 := 0; val7 < int(val6); val7++ {
			err = gobtools.DecodeString(buf, &r.OrderOnlyStrings[val7])
			if err != nil {
				return err
			}
		}
	}

	var val10 int32
	err = gobtools.DecodeSimple[int32](buf, &val10)
	if err != nil {
		return err
	}
	if val10 > 0 {
		r.GlobCache = make([]globResultCache, val10)
		for val11 := 0; val11 < int(val10); val11++ {
			if err = r.GlobCache[val11].Decode(buf); err != nil {
				return err
			}
		}
	}

	return err
}

var BuildActionCachedDataGobRegId int16

func (r BuildActionCachedData) GetTypeId() int16 {
	return BuildActionCachedDataGobRegId
}

func (r BuildActionCache) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeSimple(buf, int32(len(r))); err != nil {
		return err
	}
	for k, v := range r {
		if err = k.Encode(buf); err != nil {
			return err
		}
		val1 := v == nil
		if err = gobtools.EncodeSimple(buf, val1); err != nil {
			return err
		}
		if !val1 {
			if err = (*v).Encode(buf); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *BuildActionCache) Decode(buf *bytes.Reader) error {
	var err error

	var val1 int32
	err = gobtools.DecodeSimple[int32](buf, &val1)
	if err != nil {
		return err
	}
	if val1 > 0 {
		(*r) = make(map[BuildActionCacheKey]*BuildActionCachedData, val1)
		for val2 := 0; val2 < int(val1); val2++ {
			var k BuildActionCacheKey
			var v *BuildActionCachedData
			if err = k.Decode(buf); err != nil {
				return err
			}
			var val5 bool
			if err = gobtools.DecodeSimple(buf, &val5); err != nil {
				return err
			}
			if !val5 {
				var val4 BuildActionCachedData
				if err = val4.Decode(buf); err != nil {
					return err
				}
				v = &val4
			}
			(*r)[k] = v
		}
	}

	return err
}

var BuildActionCacheGobRegId int16

func (r BuildActionCache) GetTypeId() int16 {
	return BuildActionCacheGobRegId
}

func (r OrderOnlyStringsCache) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeSimple(buf, int32(len(r))); err != nil {
		return err
	}
	for k, v := range r {
		if err = gobtools.EncodeString(buf, k); err != nil {
			return err
		}
		if err = gobtools.EncodeSimple(buf, int32(len(v))); err != nil {
			return err
		}
		for val1 := 0; val1 < len(v); val1++ {
			if err = gobtools.EncodeString(buf, v[val1]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *OrderOnlyStringsCache) Decode(buf *bytes.Reader) error {
	var err error

	var val1 int32
	err = gobtools.DecodeSimple[int32](buf, &val1)
	if err != nil {
		return err
	}
	if val1 > 0 {
		(*r) = make(map[string][]string, val1)
		for val2 := 0; val2 < int(val1); val2++ {
			var k string
			var v []string
			err = gobtools.DecodeString(buf, &k)
			if err != nil {
				return err
			}
			var val5 int32
			err = gobtools.DecodeSimple[int32](buf, &val5)
			if err != nil {
				return err
			}
			if val5 > 0 {
				v = make([]string, val5)
				for val6 := 0; val6 < int(val5); val6++ {
					err = gobtools.DecodeString(buf, &v[val6])
					if err != nil {
						return err
					}
				}
			}
			(*r)[k] = v
		}
	}

	return err
}

var OrderOnlyStringsCacheGobRegId int16

func (r OrderOnlyStringsCache) GetTypeId() int16 {
	return OrderOnlyStringsCacheGobRegId
}
