// Code generated by go run gob_gen.go; DO NOT EDIT.

package blueprint

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	providerKeyGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(providerKey) })
}

func (r providerKey) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInt(buf, r.id); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.typ); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.mutator); err != nil {
		return err
	}
	return err
}

func (r *providerKey) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeInt(buf, &r.id)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.typ)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.mutator)
	if err != nil {
		return err
	}

	return err
}

var providerKeyGobRegId int16

func (r providerKey) GetTypeId() int16 {
	return providerKeyGobRegId
}
