// Code generated by go run gob_gen.go; DO NOT EDIT.

package test

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
	"github.com/google/blueprint/proptools"
)

// begin of test_package.go
func init() {
	TypeStructGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(TypeStruct) })
}

func (r TypeStruct) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.Name); err != nil {
		return err
	}
	return err
}

func (r TypeStruct) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":test.TypeStruct")
	hasher.WriteInt(1)
	hasher.WriteString(":.string")
	hasher.WriteString(r.Name)
	return nil
}

func (r *TypeStruct) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.Name)
	if err != nil {
		return err
	}

	return err
}

var TypeStructGobRegId int16

func (r TypeStruct) GetTypeId() int16 {
	return TypeStructGobRegId
}

// end of test_package.go
