// Code generated by go run gob_gen.go; DO NOT EDIT.

package test

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	TypeStructGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(TypeStruct) })
}

func (r TypeStruct) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	if err := r.Encode(buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r TypeStruct) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.Name); err != nil {
		return err
	}
	return nil
}

func (r *TypeStruct) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	return r.Decode(buf)
}

func (r *TypeStruct) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.Name)
	if err != nil {
		return err
	}

	return nil
}

var TypeStructGobRegId int16

func (r TypeStruct) GetTypeId() int16 {
	return TypeStructGobRegId
}
