// Code generated by go run gob_gen.go -source gob_test_data.go; DO NOT EDIT.

package main

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func (r TestStruct) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	var err error

	if err = gobtools.EncodeStruct(buf, &r.TestEcho); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeString(buf, r.f1); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, r.f2); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, r.f3); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, r.f4); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, r.f5); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeString(buf, r.f6); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeStruct(buf, &r.f7); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, r.f8); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, r.f9); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, r.f10); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.f11))); err != nil {
		return nil, err
	}
	for i := 0; i < len(r.f11); i++ {
		if err = gobtools.EncodeString(buf, r.f11[i]); err != nil {
			return nil, err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.f12))); err != nil {
		return nil, err
	}
	for k, v := range r.f12 {
		if err = gobtools.EncodeString(buf, k); err != nil {
			return nil, err
		}
		if err = gobtools.EncodeSimple(buf, int64(v)); err != nil {
			return nil, err
		}
	}

	isNil17 := r.f13 == nil
	if err = gobtools.EncodeSimple(buf, isNil17); err != nil {
		return nil, err
	}
	if !isNil17 {
		if err = gobtools.EncodeString(buf, *r.f13); err != nil {
			return nil, err
		}
	}

	if err = gobtools.EncodeSimple(buf, int64(r.f14)); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.f15))); err != nil {
		return nil, err
	}
	for i := 0; i < len(r.f15); i++ {
		if err = gobtools.EncodeSimple(buf, int64(r.f15[i])); err != nil {
			return nil, err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.f16))); err != nil {
		return nil, err
	}
	for i := 0; i < len(r.f16); i++ {
		if err = gobtools.EncodeStruct(buf, &r.f16[i]); err != nil {
			return nil, err
		}
	}

	isNil24 := r.f17 == nil
	if err = gobtools.EncodeSimple(buf, isNil24); err != nil {
		return nil, err
	}
	if !isNil24 {
		if err = gobtools.EncodeStruct(buf, &*r.f17); err != nil {
			return nil, err
		}
	}

	if err = gobtools.EncodeStruct(buf, &r.f18); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeStruct(buf, &r.f19); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r *TestStruct) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	err := r.Decode(buf)
	return err
}

func (r *TestStruct) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeStruct(buf, &r.TestEcho)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.f1)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[int16](buf, &r.f2)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[int32](buf, &r.f3)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.f4)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[int64](buf, &r.f5)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.f6)
	if err != nil {
		return err
	}

	err = gobtools.DecodeStruct(buf, &r.f7)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[uint16](buf, &r.f8)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[uint32](buf, &r.f9)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[uint64](buf, &r.f10)
	if err != nil {
		return err
	}

	var val39 int32
	err = gobtools.DecodeSimple[int32](buf, &val39)
	if err != nil {
		return err
	}
	if val39 > 0 {
		r.f11 = make([]string, val39)
		for i := 0; i < int(val39); i++ {
			err = gobtools.DecodeString(buf, &r.f11[i])
			if err != nil {
				return err
			}
		}
	}

	var val41 int32
	err = gobtools.DecodeSimple[int32](buf, &val41)
	if err != nil {
		return err
	}
	if val41 > 0 {
		r.f12 = make(map[string]int, val41)
		for i := 0; i < int(val41); i++ {
			var k string
			var v int
			err = gobtools.DecodeString(buf, &k)
			if err != nil {
				return err
			}
			var val43 int64
			err = gobtools.DecodeSimple[int64](buf, &val43)
			if err != nil {
				return err
			}
			v = int(val43)
			r.f12[k] = v
		}
	}

	var isNil44 bool
	if err = gobtools.DecodeSimple(buf, &isNil44); err != nil {
		return err
	}
	if !isNil44 {
		var val44 string
		err = gobtools.DecodeString(buf, &val44)
		if err != nil {
			return err
		}
		r.f13 = &val44
	}

	var val46 int64
	err = gobtools.DecodeSimple[int64](buf, &val46)
	if err != nil {
		return err
	}
	r.f14 = int(val46)

	var val47 int32
	err = gobtools.DecodeSimple[int32](buf, &val47)
	if err != nil {
		return err
	}
	if val47 > 0 {
		r.f15 = make([]int, val47)
		for i := 0; i < int(val47); i++ {
			var val48 int64
			err = gobtools.DecodeSimple[int64](buf, &val48)
			if err != nil {
				return err
			}
			r.f15[i] = int(val48)
		}
	}

	var val49 int32
	err = gobtools.DecodeSimple[int32](buf, &val49)
	if err != nil {
		return err
	}
	if val49 > 0 {
		r.f16 = make([]TestEcho, val49)
		for i := 0; i < int(val49); i++ {
			err = gobtools.DecodeStruct(buf, &r.f16[i])
			if err != nil {
				return err
			}
		}
	}

	var isNil51 bool
	if err = gobtools.DecodeSimple(buf, &isNil51); err != nil {
		return err
	}
	if !isNil51 {
		var val51 TestEcho
		err = gobtools.DecodeStruct(buf, &val51)
		if err != nil {
			return err
		}
		r.f17 = &val51
	}

	err = gobtools.DecodeStruct(buf, &r.f18)
	if err != nil {
		return err
	}

	err = gobtools.DecodeStruct(buf, &r.f19)
	if err != nil {
		return err
	}

	return nil
}

func (r TestEcho) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	var err error

	if err = gobtools.EncodeString(buf, r.EchoStr); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r *TestEcho) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	err := r.Decode(buf)
	return err
}

func (r *TestEcho) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.EchoStr)
	if err != nil {
		return err
	}

	return nil
}
