// Code generated by go run gob_gen.go; DO NOT EDIT.

package main

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
	"github.com/google/blueprint/uniquelist"
)

func (r TestStruct) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	var err error

	if err = gobtools.EncodeStruct(buf, &r.TestEcho); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeString(buf, r.f1); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, r.f2); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, r.f3); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, r.f4); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, r.f5); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeString(buf, r.f6); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeStruct(buf, &r.f7); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, r.f8); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, r.f9); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, r.f10); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.f11))); err != nil {
		return nil, err
	}
	for i := 0; i < len(r.f11); i++ {
		if err = gobtools.EncodeString(buf, r.f11[i]); err != nil {
			return nil, err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.f12))); err != nil {
		return nil, err
	}
	for k, v := range r.f12 {
		if err = gobtools.EncodeString(buf, k); err != nil {
			return nil, err
		}
		if err = gobtools.EncodeSimple(buf, int64(v)); err != nil {
			return nil, err
		}
	}

	isNil17 := r.f13 == nil
	if err = gobtools.EncodeSimple(buf, isNil17); err != nil {
		return nil, err
	}
	if !isNil17 {
		if err = gobtools.EncodeString(buf, *r.f13); err != nil {
			return nil, err
		}
	}

	if err = gobtools.EncodeSimple(buf, int64(r.f14)); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.f15))); err != nil {
		return nil, err
	}
	for i := 0; i < len(r.f15); i++ {
		if err = gobtools.EncodeSimple(buf, int64(r.f15[i])); err != nil {
			return nil, err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.f16))); err != nil {
		return nil, err
	}
	for i := 0; i < len(r.f16); i++ {
		if err = gobtools.EncodeStruct(buf, &r.f16[i]); err != nil {
			return nil, err
		}
	}

	isNil24 := r.f17 == nil
	if err = gobtools.EncodeSimple(buf, isNil24); err != nil {
		return nil, err
	}
	if !isNil24 {
		if err = gobtools.EncodeStruct(buf, &*r.f17); err != nil {
			return nil, err
		}
	}

	if err = gobtools.EncodeStruct(buf, &r.f18); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeStruct(buf, &r.f19); err != nil {
		return nil, err
	}

	unilst28 := r.f20.ToSlice()
	if err = gobtools.EncodeSimple(buf, int32(len(unilst28))); err != nil {
		return nil, err
	}
	for i := 0; i < len(unilst28); i++ {
		if err = gobtools.EncodeStruct(buf, &unilst28[i]); err != nil {
			return nil, err
		}
	}

	unilst30 := r.f21.ToSlice()
	if err = gobtools.EncodeSimple(buf, int32(len(unilst30))); err != nil {
		return nil, err
	}
	for i := 0; i < len(unilst30); i++ {
		if err = gobtools.EncodeStruct(buf, &unilst30[i]); err != nil {
			return nil, err
		}
	}

	return buf.Bytes(), nil
}

func (r *TestStruct) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	err := r.Decode(buf)
	return err
}

func (r *TestStruct) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeStruct(buf, &r.TestEcho)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.f1)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[int16](buf, &r.f2)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[int32](buf, &r.f3)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.f4)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[int64](buf, &r.f5)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.f6)
	if err != nil {
		return err
	}

	err = gobtools.DecodeStruct(buf, &r.f7)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[uint16](buf, &r.f8)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[uint32](buf, &r.f9)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[uint64](buf, &r.f10)
	if err != nil {
		return err
	}

	var val43 int32
	err = gobtools.DecodeSimple[int32](buf, &val43)
	if err != nil {
		return err
	}
	if val43 > 0 {
		r.f11 = make([]string, val43)
		for i := 0; i < int(val43); i++ {
			err = gobtools.DecodeString(buf, &r.f11[i])
			if err != nil {
				return err
			}
		}
	}

	var val45 int32
	err = gobtools.DecodeSimple[int32](buf, &val45)
	if err != nil {
		return err
	}
	if val45 > 0 {
		r.f12 = make(map[string]int, val45)
		for i := 0; i < int(val45); i++ {
			var k string
			var v int
			err = gobtools.DecodeString(buf, &k)
			if err != nil {
				return err
			}
			var val47 int64
			err = gobtools.DecodeSimple[int64](buf, &val47)
			if err != nil {
				return err
			}
			v = int(val47)
			r.f12[k] = v
		}
	}

	var isNil48 bool
	if err = gobtools.DecodeSimple(buf, &isNil48); err != nil {
		return err
	}
	if !isNil48 {
		var val48 string
		err = gobtools.DecodeString(buf, &val48)
		if err != nil {
			return err
		}
		r.f13 = &val48
	}

	var val50 int64
	err = gobtools.DecodeSimple[int64](buf, &val50)
	if err != nil {
		return err
	}
	r.f14 = int(val50)

	var val51 int32
	err = gobtools.DecodeSimple[int32](buf, &val51)
	if err != nil {
		return err
	}
	if val51 > 0 {
		r.f15 = make([]int, val51)
		for i := 0; i < int(val51); i++ {
			var val52 int64
			err = gobtools.DecodeSimple[int64](buf, &val52)
			if err != nil {
				return err
			}
			r.f15[i] = int(val52)
		}
	}

	var val53 int32
	err = gobtools.DecodeSimple[int32](buf, &val53)
	if err != nil {
		return err
	}
	if val53 > 0 {
		r.f16 = make([]TestEcho, val53)
		for i := 0; i < int(val53); i++ {
			err = gobtools.DecodeStruct(buf, &r.f16[i])
			if err != nil {
				return err
			}
		}
	}

	var isNil55 bool
	if err = gobtools.DecodeSimple(buf, &isNil55); err != nil {
		return err
	}
	if !isNil55 {
		var val55 TestEcho
		err = gobtools.DecodeStruct(buf, &val55)
		if err != nil {
			return err
		}
		r.f17 = &val55
	}

	err = gobtools.DecodeStruct(buf, &r.f18)
	if err != nil {
		return err
	}

	err = gobtools.DecodeStruct(buf, &r.f19)
	if err != nil {
		return err
	}

	var unilst59 []TestEcho
	var val59 int32
	err = gobtools.DecodeSimple[int32](buf, &val59)
	if err != nil {
		return err
	}
	if val59 > 0 {
		unilst59 = make([]TestEcho, val59)
		for i := 0; i < int(val59); i++ {
			err = gobtools.DecodeStruct(buf, &unilst59[i])
			if err != nil {
				return err
			}
		}
	}
	r.f20 = uniquelist.Make(unilst59)

	var unilst61 []TestEchoInterface
	var val61 int32
	err = gobtools.DecodeSimple[int32](buf, &val61)
	if err != nil {
		return err
	}
	if val61 > 0 {
		unilst61 = make([]TestEchoInterface, val61)
		for i := 0; i < int(val61); i++ {
			err = gobtools.DecodeStruct(buf, &unilst61[i])
			if err != nil {
				return err
			}
		}
	}
	r.f21 = uniquelist.Make(unilst61)

	return nil
}

func (r TestEcho) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	var err error

	if err = gobtools.EncodeString(buf, r.EchoStr); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r *TestEcho) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	err := r.Decode(buf)
	return err
}

func (r *TestEcho) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.EchoStr)
	if err != nil {
		return err
	}

	return nil
}
