// Code generated by go run gob_gen.go; DO NOT EDIT.

package main

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
	"github.com/google/blueprint/gobtools/test"
	"github.com/google/blueprint/uniquelist"
)

// begin of gob_test_data.go
func init() {
	TestStructGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(TestStruct) })
	TestEchoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(TestEcho) })
	testEchosGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(testEchos) })
	testStringMapGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(testStringMap) })
	testEchoMapGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(testEchoMap) })
	TestEmbedPtrGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(TestEmbedPtr) })
	TestPtrsGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(TestPtrs) })
}

func (r TestStruct) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = r.TestEcho.Encode(ctx, buf); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.f1); err != nil {
		return err
	}

	if err = gobtools.EncodeInt16(buf, r.f2); err != nil {
		return err
	}

	if err = gobtools.EncodeInt32(buf, r.f3); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.f4); err != nil {
		return err
	}

	if err = gobtools.EncodeInt64(buf, r.f5); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.f6); err != nil {
		return err
	}

	if err = r.f7.Encode(ctx, buf); err != nil {
		return err
	}

	if err = gobtools.EncodeUint16(buf, r.f8); err != nil {
		return err
	}

	if err = gobtools.EncodeUint32(buf, r.f9); err != nil {
		return err
	}

	if err = gobtools.EncodeUint64(buf, r.f10); err != nil {
		return err
	}

	if r.f11 == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.f11)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.f11); val1++ {
			if err = gobtools.EncodeString(buf, r.f11[val1]); err != nil {
				return err
			}
		}
	}

	if r.f12 == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.f12)); err != nil {
			return err
		}
		for val2, val3 := range r.f12 {
			if err = gobtools.EncodeString(buf, val2); err != nil {
				return err
			}
			if err = gobtools.EncodeInt(buf, val3); err != nil {
				return err
			}
		}
	}

	val4 := r.f13 == nil
	if err = gobtools.EncodeBool(buf, val4); err != nil {
		return err
	}
	if !val4 {
		if err = gobtools.EncodeString(buf, (*r.f13)); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeInt(buf, r.f14); err != nil {
		return err
	}

	if r.f15 == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.f15)); err != nil {
			return err
		}
		for val5 := 0; val5 < len(r.f15); val5++ {
			if err = gobtools.EncodeInt(buf, r.f15[val5]); err != nil {
				return err
			}
		}
	}

	if r.f16 == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.f16)); err != nil {
			return err
		}
		for val6 := 0; val6 < len(r.f16); val6++ {
			if err = r.f16[val6].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	val7 := r.f17 == nil
	if err = gobtools.EncodeBool(buf, val7); err != nil {
		return err
	}
	if !val7 {
		if err = (*r.f17).Encode(ctx, buf); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.f18); err != nil {
		return err
	}

	if r.f19 == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.f19)); err != nil {
			return err
		}
		for val8 := 0; val8 < len(r.f19); val8++ {
			if err = gobtools.EncodeString(buf, r.f19[val8]); err != nil {
				return err
			}
		}
	}

	val9 := r.f20.ToSlice()
	if val9 == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(val9)); err != nil {
			return err
		}
		for val10 := 0; val10 < len(val9); val10++ {
			if err = val9[val10].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	val11 := r.f21.ToSlice()
	if val11 == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(val11)); err != nil {
			return err
		}
		for val12 := 0; val12 < len(val11); val12++ {
			if err = gobtools.EncodeInterface(ctx, buf, val11[val12]); err != nil {
				return err
			}
		}
	}

	if err = r.f22.Encode(ctx, buf); err != nil {
		return err
	}

	if r.f23 == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.f23)); err != nil {
			return err
		}
		for val13 := 0; val13 < len(r.f23); val13++ {
			if r.f23[val13] == nil {
				if err = gobtools.EncodeInt(buf, -1); err != nil {
					return err
				}
			} else {
				if err = gobtools.EncodeInt(buf, len(r.f23[val13])); err != nil {
					return err
				}
				for val14 := 0; val14 < len(r.f23[val13]); val14++ {
					if err = r.f23[val13][val14].Encode(ctx, buf); err != nil {
						return err
					}
				}
			}
		}
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.f24); err != nil {
		return err
	}

	if err = test.TypeStruct(r.f25).Encode(ctx, buf); err != nil {
		return err
	}

	if err = r.f26.Encode(ctx, buf); err != nil {
		return err
	}

	if err = r.f27.EncodeInterface(ctx, buf); err != nil {
		return err
	}

	if r.f28 == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.f28)); err != nil {
			return err
		}
		for val15, val16 := range r.f28 {
			if err = gobtools.EncodeInt(buf, val15); err != nil {
				return err
			}
			if val16 == nil {
				if err = gobtools.EncodeInt(buf, -1); err != nil {
					return err
				}
			} else {
				if err = gobtools.EncodeInt(buf, len(val16)); err != nil {
					return err
				}
				for val17 := 0; val17 < len(val16); val17++ {
					if err = gobtools.EncodeString(buf, val16[val17]); err != nil {
						return err
					}
				}
			}
		}
	}

	if r.f29 == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.f29)); err != nil {
			return err
		}
		for val18 := 0; val18 < len(r.f29); val18++ {
			if r.f29[val18] == nil {
				if err = gobtools.EncodeInt(buf, -1); err != nil {
					return err
				}
			} else {
				if err = gobtools.EncodeInt(buf, len(r.f29[val18])); err != nil {
					return err
				}
				for val19 := 0; val19 < len(r.f29[val18]); val19++ {
					if err = gobtools.EncodeString(buf, r.f29[val18][val19]); err != nil {
						return err
					}
				}
			}
		}
	}

	if err = r.f30.EncodeString(ctx, buf); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.f31); err != nil {
		return err
	}

	if r.f32 == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.f32)); err != nil {
			return err
		}
		for val20 := 0; val20 < len(r.f32); val20++ {
			val21 := r.f32[val20] == nil
			if err = gobtools.EncodeBool(buf, val21); err != nil {
				return err
			}
			if !val21 {
				if err = (*r.f32[val20]).Encode(ctx, buf); err != nil {
					return err
				}
			}
		}
	}

	if err = gobtools.EncodeString(buf, r.f33); err != nil {
		return err
	}
	if err = gobtools.EncodeString(buf, r.f34); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.f35.s); err != nil {
		return err
	}

	if err = r.f36.Encode(ctx, buf); err != nil {
		return err
	}

	val22 := r.TestEmbedPtr == nil
	if err = gobtools.EncodeBool(buf, val22); err != nil {
		return err
	}
	if !val22 {
		if err = (*r.TestEmbedPtr).Encode(ctx, buf); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeInt(buf, int(r.f38)); err != nil {
		return err
	}

	for val23 := 0; val23 < len(r.f39); val23++ {
		if err = gobtools.EncodeUint64(buf, r.f39[val23]); err != nil {
			return err
		}
	}

	if r.f40 == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.f40)); err != nil {
			return err
		}
		for val24, val25 := range r.f40 {
			for val26 := 0; val26 < len(val24); val26++ {
				if err = gobtools.EncodeString(buf, val24[val26]); err != nil {
					return err
				}
			}
			if val25 == nil {
				if err = gobtools.EncodeInt(buf, -1); err != nil {
					return err
				}
			} else {
				if err = gobtools.EncodeInt(buf, len(val25)); err != nil {
					return err
				}
				for val27, val28 := range val25 {
					if err = gobtools.EncodeInt(buf, val27); err != nil {
						return err
					}
					if val28 == nil {
						if err = gobtools.EncodeInt(buf, -1); err != nil {
							return err
						}
					} else {
						if err = gobtools.EncodeInt(buf, len(val28)); err != nil {
							return err
						}
						for val29 := 0; val29 < len(val28); val29++ {
							val30 := val28[val29] == nil
							if err = gobtools.EncodeBool(buf, val30); err != nil {
								return err
							}
							if !val30 {
								if err = gobtools.EncodeBool(buf, (*val28[val29])); err != nil {
									return err
								}
							}
						}
					}
				}
			}
		}
	}
	return err
}

func (r *TestStruct) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if err = r.TestEcho.Decode(ctx, buf); err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.f1)
	if err != nil {
		return err
	}

	err = gobtools.DecodeInt16(buf, &r.f2)
	if err != nil {
		return err
	}

	err = gobtools.DecodeInt32(buf, &r.f3)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.f4)
	if err != nil {
		return err
	}

	err = gobtools.DecodeInt64(buf, &r.f5)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.f6)
	if err != nil {
		return err
	}

	if err = r.f7.Decode(ctx, buf); err != nil {
		return err
	}

	err = gobtools.DecodeUint16(buf, &r.f8)
	if err != nil {
		return err
	}

	err = gobtools.DecodeUint32(buf, &r.f9)
	if err != nil {
		return err
	}

	err = gobtools.DecodeUint64(buf, &r.f10)
	if err != nil {
		return err
	}

	var val13 int
	err = gobtools.DecodeInt(buf, &val13)
	if err != nil {
		return err
	}
	if val13 != -1 {
		r.f11 = make([]string, val13)
		for val14 := 0; val14 < int(val13); val14++ {
			err = gobtools.DecodeString(buf, &r.f11[val14])
			if err != nil {
				return err
			}
		}
	}

	var val16 int
	err = gobtools.DecodeInt(buf, &val16)
	if err != nil {
		return err
	}
	if val16 != -1 {
		r.f12 = make(map[string]int, val16)
		for val17 := 0; val17 < int(val16); val17++ {
			var val18 string
			var val19 int
			err = gobtools.DecodeString(buf, &val18)
			if err != nil {
				return err
			}
			err = gobtools.DecodeInt(buf, &val19)
			if err != nil {
				return err
			}
			r.f12[val18] = val19
		}
	}

	var val23 bool
	if err = gobtools.DecodeBool(buf, &val23); err != nil {
		return err
	}
	if !val23 {
		var val22 string
		err = gobtools.DecodeString(buf, &val22)
		if err != nil {
			return err
		}
		r.f13 = &val22
	}

	err = gobtools.DecodeInt(buf, &r.f14)
	if err != nil {
		return err
	}

	var val27 int
	err = gobtools.DecodeInt(buf, &val27)
	if err != nil {
		return err
	}
	if val27 != -1 {
		r.f15 = make([]int, val27)
		for val28 := 0; val28 < int(val27); val28++ {
			err = gobtools.DecodeInt(buf, &r.f15[val28])
			if err != nil {
				return err
			}
		}
	}

	var val31 int
	err = gobtools.DecodeInt(buf, &val31)
	if err != nil {
		return err
	}
	if val31 != -1 {
		r.f16 = make([]TestEcho, val31)
		for val32 := 0; val32 < int(val31); val32++ {
			if err = r.f16[val32].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	var val35 bool
	if err = gobtools.DecodeBool(buf, &val35); err != nil {
		return err
	}
	if !val35 {
		var val34 TestEcho
		if err = val34.Decode(ctx, buf); err != nil {
			return err
		}
		r.f17 = &val34
	}

	if val38, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val38 == nil {
		r.f18 = nil
	} else {
		r.f18 = val38.(TestEchoInterface)
	}

	var val41 int
	err = gobtools.DecodeInt(buf, &val41)
	if err != nil {
		return err
	}
	if val41 != -1 {
		r.f19 = make([]string, val41)
		for val42 := 0; val42 < int(val41); val42++ {
			err = gobtools.DecodeString(buf, &r.f19[val42])
			if err != nil {
				return err
			}
		}
	}

	var val45 []TestEcho
	var val46 int
	err = gobtools.DecodeInt(buf, &val46)
	if err != nil {
		return err
	}
	if val46 != -1 {
		val45 = make([]TestEcho, val46)
		for val47 := 0; val47 < int(val46); val47++ {
			if err = val45[val47].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}
	r.f20 = uniquelist.Make(val45)

	var val50 []TestEchoInterface
	var val51 int
	err = gobtools.DecodeInt(buf, &val51)
	if err != nil {
		return err
	}
	if val51 != -1 {
		val50 = make([]TestEchoInterface, val51)
		for val52 := 0; val52 < int(val51); val52++ {
			if val54, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val54 == nil {
				val50[val52] = nil
			} else {
				val50[val52] = val54.(TestEchoInterface)
			}
		}
	}
	r.f21 = uniquelist.Make(val50)

	if err = r.f22.Decode(ctx, buf); err != nil {
		return err
	}

	var val57 int
	err = gobtools.DecodeInt(buf, &val57)
	if err != nil {
		return err
	}
	if val57 != -1 {
		r.f23 = make([]test.TypeAlias, val57)
		for val58 := 0; val58 < int(val57); val58++ {
			var val61 int
			err = gobtools.DecodeInt(buf, &val61)
			if err != nil {
				return err
			}
			if val61 != -1 {
				r.f23[val58] = make([]test.TypeStruct, val61)
				for val62 := 0; val62 < int(val61); val62++ {
					if err = r.f23[val58][val62].Decode(ctx, buf); err != nil {
						return err
					}
				}
			}
		}
	}

	if val65, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val65 == nil {
		r.f24 = nil
	} else {
		r.f24 = val65.(test.TypeInterface)
	}

	var val67 test.TypeStruct
	if err = val67.Decode(ctx, buf); err != nil {
		return err
	}
	r.f25 = test.TypeIdent(val67)

	if err = r.f26.Decode(ctx, buf); err != nil {
		return err
	}

	if err = r.f27.DecodeInterface(ctx, buf); err != nil {
		return err
	}

	var val71 int
	err = gobtools.DecodeInt(buf, &val71)
	if err != nil {
		return err
	}
	if val71 != -1 {
		r.f28 = make(map[int][]string, val71)
		for val72 := 0; val72 < int(val71); val72++ {
			var val73 int
			var val74 []string
			err = gobtools.DecodeInt(buf, &val73)
			if err != nil {
				return err
			}
			var val77 int
			err = gobtools.DecodeInt(buf, &val77)
			if err != nil {
				return err
			}
			if val77 != -1 {
				val74 = make([]string, val77)
				for val78 := 0; val78 < int(val77); val78++ {
					err = gobtools.DecodeString(buf, &val74[val78])
					if err != nil {
						return err
					}
				}
			}
			r.f28[val73] = val74
		}
	}

	var val81 int
	err = gobtools.DecodeInt(buf, &val81)
	if err != nil {
		return err
	}
	if val81 != -1 {
		r.f29 = make([][]string, val81)
		for val82 := 0; val82 < int(val81); val82++ {
			var val84 int
			err = gobtools.DecodeInt(buf, &val84)
			if err != nil {
				return err
			}
			if val84 != -1 {
				r.f29[val82] = make([]string, val84)
				for val85 := 0; val85 < int(val84); val85++ {
					err = gobtools.DecodeString(buf, &r.f29[val82][val85])
					if err != nil {
						return err
					}
				}
			}
		}
	}

	if err = r.f30.DecodeString(ctx, buf); err != nil {
		return err
	}

	if val89, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val89 == nil {
		r.f31 = nil
	} else {
		r.f31 = val89
	}

	var val91 int
	err = gobtools.DecodeInt(buf, &val91)
	if err != nil {
		return err
	}
	if val91 != -1 {
		r.f32 = make([]*test.TypeStruct, val91)
		for val92 := 0; val92 < int(val91); val92++ {
			var val94 bool
			if err = gobtools.DecodeBool(buf, &val94); err != nil {
				return err
			}
			if !val94 {
				var val93 test.TypeStruct
				if err = val93.Decode(ctx, buf); err != nil {
					return err
				}
				r.f32[val92] = &val93
			}
		}
	}

	err = gobtools.DecodeString(buf, &r.f33)
	if err != nil {
		return err
	}
	err = gobtools.DecodeString(buf, &r.f34)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.f35.s)
	if err != nil {
		return err
	}

	if err = r.f36.Decode(ctx, buf); err != nil {
		return err
	}

	var val102 bool
	if err = gobtools.DecodeBool(buf, &val102); err != nil {
		return err
	}
	if !val102 {
		var val101 TestEmbedPtr
		if err = val101.Decode(ctx, buf); err != nil {
			return err
		}
		r.TestEmbedPtr = &val101
	}

	var val105 int
	err = gobtools.DecodeInt(buf, &val105)
	if err != nil {
		return err
	}
	r.f38 = test.TypeBasic(val105)

	for val108 := 0; val108 < len(r.f39); val108++ {
		err = gobtools.DecodeUint64(buf, &r.f39[val108])
		if err != nil {
			return err
		}
	}

	var val110 int
	err = gobtools.DecodeInt(buf, &val110)
	if err != nil {
		return err
	}
	if val110 != -1 {
		r.f40 = make(map[[1]string]map[int][]*bool, val110)
		for val111 := 0; val111 < int(val110); val111++ {
			var val112 [1]string
			var val113 map[int][]*bool
			for val115 := 0; val115 < len(val112); val115++ {
				err = gobtools.DecodeString(buf, &val112[val115])
				if err != nil {
					return err
				}
			}
			var val117 int
			err = gobtools.DecodeInt(buf, &val117)
			if err != nil {
				return err
			}
			if val117 != -1 {
				val113 = make(map[int][]*bool, val117)
				for val118 := 0; val118 < int(val117); val118++ {
					var val119 int
					var val120 []*bool
					err = gobtools.DecodeInt(buf, &val119)
					if err != nil {
						return err
					}
					var val123 int
					err = gobtools.DecodeInt(buf, &val123)
					if err != nil {
						return err
					}
					if val123 != -1 {
						val120 = make([]*bool, val123)
						for val124 := 0; val124 < int(val123); val124++ {
							var val126 bool
							if err = gobtools.DecodeBool(buf, &val126); err != nil {
								return err
							}
							if !val126 {
								var val125 bool
								err = gobtools.DecodeBool(buf, &val125)
								if err != nil {
									return err
								}
								val120[val124] = &val125
							}
						}
					}
					val113[val119] = val120
				}
			}
			r.f40[val112] = val113
		}
	}

	return err
}

var TestStructGobRegId int16

func (r TestStruct) GetTypeId() int16 {
	return TestStructGobRegId
}

func (r TestEcho) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.EchoStr); err != nil {
		return err
	}
	return err
}

func (r *TestEcho) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.EchoStr)
	if err != nil {
		return err
	}

	return err
}

var TestEchoGobRegId int16

func (r TestEcho) GetTypeId() int16 {
	return TestEchoGobRegId
}

func (r testEchos) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r); val1++ {
			if err = gobtools.EncodeInterface(ctx, buf, r[val1]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *testEchos) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		(*r) = make([]TestEchoInterface, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			if val5, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val5 == nil {
				(*r)[val3] = nil
			} else {
				(*r)[val3] = val5.(TestEchoInterface)
			}
		}
	}

	return err
}

var testEchosGobRegId int16

func (r testEchos) GetTypeId() int16 {
	return testEchosGobRegId
}

func (r testStringMap) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r)); err != nil {
			return err
		}
		for val1, val2 := range r {
			if err = gobtools.EncodeString(buf, val1); err != nil {
				return err
			}
			if val2 == nil {
				if err = gobtools.EncodeInt(buf, -1); err != nil {
					return err
				}
			} else {
				if err = gobtools.EncodeInt(buf, len(val2)); err != nil {
					return err
				}
				for val3 := 0; val3 < len(val2); val3++ {
					if err = gobtools.EncodeString(buf, val2[val3]); err != nil {
						return err
					}
				}
			}
		}
	}
	return err
}

func (r *testStringMap) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val1 int
	err = gobtools.DecodeInt(buf, &val1)
	if err != nil {
		return err
	}
	if val1 != -1 {
		(*r) = make(map[string][]string, val1)
		for val2 := 0; val2 < int(val1); val2++ {
			var val3 string
			var val4 []string
			err = gobtools.DecodeString(buf, &val3)
			if err != nil {
				return err
			}
			var val7 int
			err = gobtools.DecodeInt(buf, &val7)
			if err != nil {
				return err
			}
			if val7 != -1 {
				val4 = make([]string, val7)
				for val8 := 0; val8 < int(val7); val8++ {
					err = gobtools.DecodeString(buf, &val4[val8])
					if err != nil {
						return err
					}
				}
			}
			(*r)[val3] = val4
		}
	}

	return err
}

var testStringMapGobRegId int16

func (r testStringMap) GetTypeId() int16 {
	return testStringMapGobRegId
}

func (r testEchoMap) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r)); err != nil {
			return err
		}
		for val1, val2 := range r {
			if err = val1.Encode(ctx, buf); err != nil {
				return err
			}
			val3 := val2 == nil
			if err = gobtools.EncodeBool(buf, val3); err != nil {
				return err
			}
			if !val3 {
				if err = (*val2).Encode(ctx, buf); err != nil {
					return err
				}
			}
		}
	}
	return err
}

func (r *testEchoMap) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val1 int
	err = gobtools.DecodeInt(buf, &val1)
	if err != nil {
		return err
	}
	if val1 != -1 {
		(*r) = make(map[TestEcho]*TestEcho, val1)
		for val2 := 0; val2 < int(val1); val2++ {
			var val3 TestEcho
			var val4 *TestEcho
			if err = val3.Decode(ctx, buf); err != nil {
				return err
			}
			var val7 bool
			if err = gobtools.DecodeBool(buf, &val7); err != nil {
				return err
			}
			if !val7 {
				var val6 TestEcho
				if err = val6.Decode(ctx, buf); err != nil {
					return err
				}
				val4 = &val6
			}
			(*r)[val3] = val4
		}
	}

	return err
}

var testEchoMapGobRegId int16

func (r testEchoMap) GetTypeId() int16 {
	return testEchoMapGobRegId
}

func (r TestEmbedPtr) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.f37); err != nil {
		return err
	}
	return err
}

func (r *TestEmbedPtr) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.f37)
	if err != nil {
		return err
	}

	return err
}

var TestEmbedPtrGobRegId int16

func (r TestEmbedPtr) GetTypeId() int16 {
	return TestEmbedPtrGobRegId
}

func (r TestPtrs) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	val1 := r.f1 == nil
	if err = gobtools.EncodeBool(buf, val1); err != nil {
		return err
	}
	if !val1 {
		if err = (*r.f1).Encode(ctx, buf); err != nil {
			return err
		}
	}

	val2 := r.f2 == nil
	if err = gobtools.EncodeBool(buf, val2); err != nil {
		return err
	}
	if !val2 {
		if err = (*r.f2).Encode(ctx, buf); err != nil {
			return err
		}
	}
	return err
}

func (r *TestPtrs) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 bool
	if err = gobtools.DecodeBool(buf, &val2); err != nil {
		return err
	}
	if !val2 {
		var val1 TestEcho
		if err = val1.Decode(ctx, buf); err != nil {
			return err
		}
		r.f1 = &val1
	}

	var val5 bool
	if err = gobtools.DecodeBool(buf, &val5); err != nil {
		return err
	}
	if !val5 {
		var val4 TestEcho
		if err = val4.Decode(ctx, buf); err != nil {
			return err
		}
		r.f2 = &val4
	}

	return err
}

var TestPtrsGobRegId int16

func (r TestPtrs) GetTypeId() int16 {
	return TestPtrsGobRegId
}

// end of gob_test_data.go
